Api v0
D4-project/d4-core pull request #24
Opened 2019-09-02 14:15 UTC by Terrtia

Add users managements + API (sensor registration)

2019-09-02 18:12 UTC, adulau requested changes
Looks very good. Just some minor stuff. Thanks a lot for the work!

2019-09-02 18:12 UTC, adulau commented on server/web/blueprints/restApi.py
> +    else:
You can remove the else and return False by default to avoid edge cases.

Another (potential) issue is the side-channel attack to test token, maybe adding a small random delay could help.

2019-09-02 18:12 UTC, adulau commented on server/web/blueprints/settings.py
> +    if result:
Maybe simplify the code to return directly the result?

2019-09-02 18:12 UTC, adulau commented on server/web/templates/server_management.html
> +	{% include 'navbar.html' %}
:+1: I love the navbar simplification!

2019-09-03 08:48 UTC, Terrtia commented
API + login protection added:
- brute force
- side-channel attack

2019-09-17 07:04 UTC, merged